jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Docker image
          command: |
            docker build -t tuhinmas/devops-sanber:latest -f docker/Dockerfile .
            docker images

      - run:
          name: Login registry
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

      - run:
          name: Push
          command: docker push tuhinmas/devops-sanber:latest

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Setup SSH key
          command: |
            mkdir -p ~/.ssh
            printf "%s" "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

      - run:
          name: Deploy
          command: |
            ssh -vvv $SSH_USER@$SSH_HOST "
            docker pull tuhinmas/devops-sanber:latest &&
            docker compose up -d"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build